version: '3.3'
services:
  docker-mysql:
    image: mysql:8.0
    container_name: docker-mysql
    volumes:
      - /ebsMyResto/mysql-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 0D2B87E1DE55A9BD89009B37979CACD984AA773C7197BE3F46DCB15B0CAE7E6D
      MYSQL_DATABASE: myresto
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springuser
    ports:
      - "3306:3306"
  phpmyadmin:
    restart: always
    container_name: phpmyadmin
    depends_on:
      - docker-mysql
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: docker-mysql
  spring:
    container_name: springapp
    restart: always
    image: myresto:latest
    ports:
      - "5000:5000"
    volumes:
      - /ebsMyResto/images:/images
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql/myresto?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: springuser
      APP_PORT: 5000
    depends_on:
      - docker-mysql
