---
- hosts: all
  become: true
  pre_tasks:
    - name: install dependencies
      apt:
        name: "git"
        state: "present"
    - name: install dependencies
      apt:
        name: "docker"
        state: "present"
    - name: install dependencies
      apt:
        name: "docker-compose"
        state: "present"
  tasks:
    - name: "Download data from git repo"
      git:
        repo: 'https://github.com/MaximeDzN/myResto-spring.git'
        version: 'DevOps'
        dest: '/home/ubuntu/myResto-spring'
    - name: "Build an image for MyResto"
      docker_image:
        build:
          path: /home/ubuntu/myResto-spring/Docker
        name: myresto
        tag: latest
        push: no
        source: build
    - name: "docker-compose up database"
      command: "docker-compose -f /home/ubuntu/myResto-spring/Docker/docker-compose.yml up -d docker-mysql"

    - name: "docker-compose up for phpmyadmin and springboot app"
      command: "docker-compose -f /home/ubuntu/myResto-spring/Docker/docker-compose.yml up -d"
