---
- hosts: all
  become: true
  pre_tasks:
    - name: install dependencies docker 
      command: "sudo amazon-linux-extras install -y  docker"

    - name: install dependencies docker
      command: "sudo yum install -y docker"

    - name: start docker
      command: "sudo service docker start"

    - name: enable docker
      command: "sudo systemctl enable docker"

    - name: ajout droit docker a ec2
      command: "sudo usermod -a -G docker ec2-user"

    - name: install docker-compose
      shell: 'sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose'

    - name: ajout droit docker-compose
      command: "sudo chmod +x /usr/local/bin/docker-compose" 

  tasks:
    - name: "Download data from git repo"
      git:
        repo: 'https://github.com/MaximeDzN/myResto-spring.git'
        version: 'DevOps'
        dest: '/home/ec2-user/myResto-spring'

    - name: Go to the folder and execute command
      command: chdir=/home/ec2-user/myResto-spring/Docker ls

    # - name: "Build an image for MyResto"
    #   command: "docker build -f /home/ec2-user/myResto-spring/Docker/Dockerfile -t myresto ."
      
    - name: "docker-compose up database"
      command: "docker-compose up -d docker-mysql"


    # - name: "docker-compose up for phpmyadmin and springboot app"
    #   shell: "docker-compose -f /home/ec2-user/myResto-spring/Docker/docker-compose.yaml up -d phpmyadmin"
